### PR TITLE
Khangbbt

### PR DESCRIPTION
**Pull request by khang72**
Codeforces Problem 466c Number of Ways. Pull request for Hacktoberfest 2017 ^^

### CODE REVIEW

**Comment by gopalgoel** [comment]
Add all the files you have at once. Will be easier.

**Comment by gopalgoel** [comment]
@khang72 I think you created another pull request with same files. I think this PR can be closed now. Right?

**Comment by khang72** [comment]
I am trying to make another pull request for another problem, but I am still struggling. I am sorry. I will fix it.

**Comment by gopalgoel** [comment]
@khang72 No worries. We are here to help. Ask if facing trouble. Add all files in one PR. Close the other one. It will be nice to track.

**Pull request closed without merging**
