### PR TITLE
added 869b.cpp solution

### PR DESCRIPTION
**Pull request by tezansahu**
This time I have done it in the originally made "codeforces" directory

### CODE REVIEW

**Comment by gopalgoel** [comment]
Close the PR.

**Comment by tezansahu** [comment]
Done

**Comment by gopalgoel** [comment]
Do you have more solutions to add in this PR?

**Comment by tezansahu** [comment]
sorry, not currently. But I would like to work on a few more problems in the near future and would send you pull requests regarding the same when I complete the codes

**Comment by tezansahu** [comment]
I have added another solution. I am closing this PR n sending u another one....

**Pull request closed without merging**
